### ISSUE TITLE
Ошибка в плагине

### ISSUE THREAD

**Issue by GulomovCreative** [Boshnik/Counters#1]
В версии 1.0.2 изменил способ получения объектов в плагине на getCollection, который возвращает массив с объектами, а в итерации обращаешься как к массиву:

```
<?php
/** @var modX $modx */
if($modx->event->name == 'OnWebPageInit') {
    $modx->addPackage('counters', MODX_CORE_PATH . 'components/counters/model/');
    $counters = $modx->getCollection('CountersItem');
    foreach($counters as $counter) {
        if($counter['active'] && ($counter['all_context'] || $modx->context->key == $counter['context'])) {
            $code = $counter['content'];
            if($counter['position'] == 'Head') {
                $modx->regClientStartupHTMLBlock($code);
            } else {
                $modx->regClientHTMLBlock($code);
            }
        }
    }
}
```

**Comment by Boshnik** [comment]
В вашем коде не хватает строчки
`$counter = $counter->toArray();`

**Comment by GulomovCreative** [comment]
@Boshnik я понимаю, я имею ввиду что в modstore лежит версия в которой есть эта ошибка

![Аннотация 2019-12-23 163038](https://user-images.githubusercontent.com/20814058/71349182-f2663100-25a0-11ea-9316-bb47dc213c61.png)

**Comment by Boshnik** [comment]
Да, действительно. Спасибо
